name: WorldGuardRegionProtect
author: RitaSister
version: 0.7.0-pre4
main: net.ritasister.wgrp.WorldGuardRegionProtect
softdepend: [ WorldGuard ]
description: Protect your region in the server.
api-version: 1.13
commands:
  worldguardregionprotect:
   aliases: [wgrp]