name: WorldGuardRegionProtect
author: RitaSister
version: 0.7.1-pre5
main: net.ritasister.wgrp.WorldGuardRegionProtect
softdepend: [ WorldGuard ]
description: Protect your region in the server.
api-version: 1.16
commands:
  worldguardregionprotect:
   aliases: [wgrp]