name: ServerRegionProtect
author: RitaSister
version: 0.6.1
main: net.ritasister.srp.ServerRegionProtect
softdepend: [ WorldGuard ]
description: Protect your region in the server.
api-version: 1.13
commands:
  serverregionprotect:
   aliases: [srp]