name: WorldGuardRegionProtect
author: RitaSister
version: 0.7.1-pre1
main: net.ritasister.wgrp.WorldGuardRegionProtect
softdepend: [ WorldGuard ]
description: Protect your region in the server.
api-version: 1.18
commands:
  worldguardregionprotect:
   aliases: [wgrp]