#-------------------------------------------------------------
# Basic configuration settings for the plugin.
#-------------------------------------------------------------
wgRegionProtect:

  #-------------------------------------------------------------
  # Language of this plugins.
  # Loaded languages uploaded in "lang" folder.
  # Languages available:
  # en_US, de_DE, fi_FI, fr_FR, ru_RU, zh_CN, uk_UA, ja_JP
  #-------------------------------------------------------------
  lang: en_US

  #-------------------------------------------------------------
  # List of protected regions.
  # If regions are not needed, specify an empty parameter:
  # Do not delete all worlds, always leave one world,
  # otherwise the structure of the configuration is broken!
  # regionProtect: []
  #   example_world: []
  #-------------------------------------------------------------
  regionProtect:
    world:
      - spawn
      - pvp

  #--------------------------------------------------------------------------------------
  # List of protected regions where breaking is allowed.
  # If regions are not needed, specify an empty parameter:
  # Do not delete all worlds, always leave one world,
  # otherwise the structure of the configuration is broken!
  # regionProtectAllow: []
  #   another_world: []
  #--------------------------------------------------------------------------------------
  regionProtectAllow:
    another_world: []

  #--------------------------------------------------------------------------------------
  # List of protected regions where only breaking is allowed.
  # If regions are not needed, specify an empty parameter:
  # Do not delete all worlds, always leave one world,
  # otherwise the structure of the configuration is broken!
  # regionProtectOnlyBreakAllow:
  #   another_world: []
  #--------------------------------------------------------------------------------------
  regionProtectOnlyBreakAllow:
    another_world: []

  #--------------------------------------------------------------------------------------
  # List of prohibited entity / block for interaction in the protected region.
  # If you don't want to block it, specify an empty parameter:
  #
  # Attention! In interact_type, the block IDs\items are different from Minecraft!
  # list of blocks prohibited by default\items:
  # - armor_stand
  # - end_crystal
  # - minecart
  # - tnt_minecart
  # - command_block_minecart
  # - hopper_minecart
  # - chest_minecart
  # - furnace_minecart
  # - oak_boat
  # - acacia_boat
  # - spruce_boat
  # - birch_boat
  # - jungle_boat
  # - jungle_boat
  # - dark_oak_boat
  # - bucket
  # - water_bucket
  # - lava_bucket
  #
  # interactType: []
  #--------------------------------------------------------------------------------------
  protectInteract:
    interactType:
      - armor_stand
      - end_crystal
      - minecart
      - tnt_minecart
      - command_block_minecart
      - hopper_minecart
      - chest_minecart
      - furnace_minecart
      - oak_boat
      - acacia_boat
      - spruce_boat
      - birch_boat
      - jungle_boat
      - jungle_boat
      - dark_oak_boat
      - bucket
      - water_bucket
      - lava_bucket
    #--------------------------------------------------------------------------------------
    # collisionWithVehicle - whether the player can collide with a vehicle. (Boat, Wagon, etc.)
    # canSitAsPassengerInVehicle - whether the player can sit as a passenger in the vehicle.
    # canDamageVehicle - whether the player can damage the vehicle.
    # canTakeLecternBookle - whether the player can take a book from the pulpit.
    #--------------------------------------------------------------------------------------
    player:
      collisionWithVehicle: true
      canSitAsPassengerInVehicle: true
      canDamageVehicle: true
      canTakeLecternBook: true

  #--------------------------------------------------------------------------------------
  # List of forbidden commands from WE / FAWE.
  #--------------------------------------------------------------------------------------
  noProtectCmd:
    cmdWe:
    - //set
    - //replace
    - //overlay
    - //walls
    - //deform
    - //fill
    - //fillr
    - //fixlava
    - //hollow
    - //move
    - //stack
    - //smooth
    - //cut
    - //replacenear
    cmdWeC:
    - //cyl
    - //hcyl
    - //drain
    - //rep
    cmdWeP:
    - //pyramid
    - //hpyramid
    cmdWeS:
    - //sphere
    - //hsphere
    cmdWeU:
    - //up
    - /up
    cmdWeCP:
    - //paste
    - //place
    - //replacenear
    - //hollow

  #--------------------------------------------------------------------------------------
  # Turn Enable/Disable the exploding from Entity(tnt, creeper and etc.).
  #--------------------------------------------------------------------------------------
  explodeEntity:
    enable: true

  #--------------------------------------------------------------------------------------
  # Turn Enable/Disable the notification if player try to use in the protected region WE\FAWE command.
  #--------------------------------------------------------------------------------------
  spySettings:
    notify:
      #--------------------------------------------------------------------------------------
      # Enable notify of action for admin and console.
      #--------------------------------------------------------------------------------------
      console:
        enable: true
      admin:
        enable: true
      #--------------------------------------------------------------------------------------
      # Settings of sound for admin.
      #--------------------------------------------------------------------------------------
      sound:
        enable: true
        #--------------------------------------------------------------------------------------
        # All sounds can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
        #--------------------------------------------------------------------------------------
        type: BLOCK_ANVIL_PLACE

    #--------------------------------------------------------------------------------------
    # A list of commands that will be tracked in the /wgrp spy command
    #--------------------------------------------------------------------------------------
    spyCommandList:
      - //set
      - //replace
      - //overlay
      - //walls
      - //deform
      - //fill
      - //fillr
      - //fixlava
      - //hollow
      - //move
      - //stack
      - //smooth
      - //cut
      - //replacenear

  #--------------------------------------------------------------------------------------
  # Turn Enable/Disable the protected region message.
  #--------------------------------------------------------------------------------------
  regionMessageProtect: true

  #--------------------------------------------------------------------------------------
  # Turn Enable/Disable the protected region message when using the WE\FAWE commands.
  #--------------------------------------------------------------------------------------
  regionMessageProtectWe: true

  #--------------------------------------------------------------------------------------
  # Settings of database.
  #--------------------------------------------------------------------------------------
  dataSource:
    enable: false
    database: wgrp_core
    host: localhost
    port: 3306
    user: root
    password: root
    table: wgrp_logs
    useSsl: true

    #--------------------------------------------------------------------------------------
    # Pool settings...
    #--------------------------------------------------------------------------------------
    maxPoolSize: 10
    maxLifetime: 1800
    connectionTimeout: 5000
    intervalReload: 60