# -------------------------------------------------------------
# Basic configuration settings for the plugin.
# -------------------------------------------------------------
wgRegionProtect:

    # -------------------------------------------------------------
    # Language of this plugins.
    # Loaded languages uploaded in "lang" folder.
    # Languages available:
    # en_US, de_DE, fi_FI, fr_FR, ru_RU, zh_CN, uk_UA, ja_JP
    # -------------------------------------------------------------
    lang: en_US

    # -------------------------------------------------------------
    # Let the admin know if he updated the plugin to the latest version.
    # -------------------------------------------------------------
    updateChecker: true

    # -------------------------------------------------------------
    # List of protected regions.
    # If regions are not needed, specify an empty parameter:
    # Do not delete all worlds, always leave one world,
    # otherwise the structure of the configuration is broken!
    # regionProtect: []
    #   another_world: []
    # -------------------------------------------------------------
    regionProtect:
        world:
            - spawn
            - pvp

    # --------------------------------------------------------------------------------------
    # List of protected regions where breaking is allowed.
    # If regions are not needed, specify an empty parameter:
    # Do not delete all worlds, always leave one world,
    # otherwise the structure of the configuration is broken!
    # regionProtectAllow: []
    #   another_world: []
    # --------------------------------------------------------------------------------------
    regionProtectAllow:
        another_world: []
        world: []

    # --------------------------------------------------------------------------------------
    # List of protected regions where only breaking is allowed.
    # If regions are not needed, specify an empty parameter:
    # Do not delete all worlds, always leave one world,
    # otherwise the structure of the configuration is broken!
    # regionProtectOnlyBreakAllow:
    #   another_world: []
    # --------------------------------------------------------------------------------------
    regionProtectOnlyBreakAllow:
        another_world: []
        world: []

    # --------------------------------------------------------------------------------------
    # List of prohibited entity / block for interaction in the protected region.
    # If you don't want to block it, specify an empty parameter:
    #
    # Attention! In interact_type, the block IDs\items are different from Minecraft!
    # list of blocks prohibited by default\items:
    # - armor_stand
    #    - end_crystal
    #    - minecart
    #    - tnt_minecart
    #    - command_block_minecart
    #    - hopper_minecart
    #    - chest_minecart
    #    - furnace_minecart
    #    - oak_boat
    #    - oak_chest_boat
    #    - spruce_boat
    #    - spruce_chest_boat
    #    - birch_boat
    #    - birch_chest_boat
    #    - jungle_boat
    #    - jungle_chest_boat
    #    - acacia_boat
    #    - acacia_chest_boat
    #    - dark_oak_boat
    #    - dark_oak_chest_boat
    #    - mangrove_boat
    #    - mangrove_chest_boat
    #    - bucket
    #    - water_bucket
    #    - lava_bucket
    #    - tropical_fish_bucket
    #    - pufferfish_bucket
    #    - axolotl_bucket
    #    - cod_bucket
    #    - salmon_bucket
    #    - tadpole_bucket
    #
    # interactType: []
    # --------------------------------------------------------------------------------------
    protectInteract:
        # --------------------------------------------------------------------------------------
        # Checked for break, place, changing in the item frame, glow item frame and break/place painting
        # --------------------------------------------------------------------------------------
        interactType:
            - armor_stand
            - end_crystal
            - bucket
            - water_bucket
            - lava_bucket
            - tropical_fish_bucket
            - pufferfish_bucket
            - axolotl_bucket
            - cod_bucket
            - salmon_bucket
            - tadpole_bucket
            - item_frame
            - glow_item_frame
            - painting
        # --------------------------------------------------------------------------------------
        # All list of available of creature mob:
        # - axolotl
        # - squid
        # - dolphin
        # - glow_squid
        # - cod
        # - tropical_fish
        # - salmon
        # - pufferfish
        # - donkey
        # - parrot
        # - allay
        # - trader_llama
        # - horse
        # - polar_bear
        # - ocelot
        # - cat
        # - frog
        # - cow
        # - fox
        # - mushroom_cow
        # - zombie_horse
        # - panda
        # - bee
        # - skeleton_horse
        # - pig
        # - llama
        # - goat
        # - wolf
        # - chicken
        # - sniffer
        # - sheep
        # - rabbit
        # - turtle
        # - wandering_trader
        # - mule
        # - tadpole
        # - camel
        # --------------------------------------------------------------------------------------
        creatureType:
            - tropical_fish
            - axolotl
            - turtle
            - sniffer
            - camel
        monstersType:
            - zombie
        entityExplodeType:
            - primed_tnt
            - end_crystal
            - minecart_tnt
            - creeper
            - wither_skull
        vehicleType:
            - minecart
            - tnt_minecart
            - command_block_minecart
            - hopper_minecart
            - chest_minecart
            - furnace_minecart
            - oak_boat
            - oak_chest_boat
            - spruce_boat
            - spruce_chest_boat
            - birch_boat
            - birch_chest_boat
            - jungle_boat
            - jungle_chest_boat
            - acacia_boat
            - acacia_chest_boat
            - dark_oak_boat
            - dark_oak_chest_boat
            - mangrove_boat
            - mangrove_chest_boat
            - cherry_boat
            - cherry_chest_boat
            - bamboo_raft
            - bamboo_chest_raft
        naturalBlockOrItem:
            - oak_sapling
            - spruce_sapling
            - birch_sapling
            - jungle_sapling
            - dark_oak_sapling
            - mangrove_propagule
            - dead_bush
            - fern
            - azalea
            - flowering_azalea
            - dandelion
            - poppy
            - blue_orchid
            - allium
            - azure_bluet
            - red_tulip
            - orange_tulip
            - white_tulip
            - pink_tulip
            - oxeye_daisy
            - cornflower
            - lily_of_the_valley
            - bamboo
            - sugar_cane
            - cactus
            - wither_rose
            - crimson_roots
            - warped_roots
            - cherry_sapling
            - torchflower
        # --------------------------------------------------------------------------------------
        # denyCollisionWithVehicle — whether the player can collide with a vehicle. (Boat, Wagon, etc.)
        # denySitAsPassengerInVehicle — whether the player can sit as a passenger in the vehicle.
        # denyDamageVehicle — whether the player can damage the vehicle.
        # denyTakeLecternBook — whether the player can take a book from the pulpit.
        # denyStonecutterRecipeSelect- whether the player can use stonecutter for any recipe.
        # denyLoomPatternSelect - whether the player can use loom for select pattern for banner.
        # denyTakeOrPlaceNaturalBlockOrItemIOFlowerPot - whether the player can manipulate with flower pot.
        # --------------------------------------------------------------------------------------
        player:
            denyCollisionWithVehicle: true
            denySitAsPassengerInVehicle: true
            denyDamageVehicle: true
            denyTakeLecternBook: true
            denyStonecutterRecipeSelect: true
            denyLoomPatternSelect: true
            denyTakeOrPlaceNaturalBlockOrItemIOFlowerPot: true
        # --------------------------------------------------------------------------------------
        # denyWaterFlowToRegion — Whether to allow water to flow into protected regions.
        # denyLavaFlowToRegion — Whether to allow lava to flow into protected regions.
        # --------------------------------------------------------------------------------------
        other:
            denyWaterFlowToRegion: true
            denyLavaFlowToRegion: true

    # --------------------------------------------------------------------------------------
    # List of forbidden commands from WE / FAWE.
    # --------------------------------------------------------------------------------------
    noProtectCmd:
        cmdWe:
            - //set
            - //replace
            - //overlay
            - //walls
            - //deform
            - //fill
            - //fillr
            - //fixlava
            - //hollow
            - //move
            - //stack
            - //smooth
            - //cut
            - //replacenear
        cmdWeC:
            - //cyl
            - //hcyl
            - //drain
            - //rep
        cmdWeP:
            - //pyramid
            - //hpyramid
        cmdWeS:
            - //sphere
            - //hsphere
        cmdWeU:
            - //up
            - /up
        cmdWeCP:
            - //paste
            - //place
            - //replacenear
            - //hollow

    # --------------------------------------------------------------------------------------
    # Turn Enable/Disable the exploding from Entity(tnt, creeper and etc.).
    # --------------------------------------------------------------------------------------
    explodeEntity:
        enable: true

    # --------------------------------------------------------------------------------------
    # Turn Enable/Disable the notification if player try to use in the protected region WE\FAWE command.
    # --------------------------------------------------------------------------------------
    spySettings:
        notify:
            # --------------------------------------------------------------------------------------
            # Enable notify of action for admin and console.
            # --------------------------------------------------------------------------------------
            console:
                enable: true
            admin:
                enable: true
            # --------------------------------------------------------------------------------------
            # Settings of sound for admin.
            # --------------------------------------------------------------------------------------
            sound:
                enable: true
                # --------------------------------------------------------------------------------------
                # All sounds can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
                # --------------------------------------------------------------------------------------
                type: BLOCK_ANVIL_PLACE

        # --------------------------------------------------------------------------------------
        # A list of commands that will be tracked in the /wgrp spy command
        # --------------------------------------------------------------------------------------
        spyCommandList:
            - //set
            - //replace
            - //overlay
            - //walls
            - //deform
            - //fill
            - //fillr
            - //fixlava
            - //hollow
            - //move
            - //stack
            - //smooth
            - //cut
            - //replacenear

    # --------------------------------------------------------------------------------------
    # Turn Enable/Disable the protected region message.
    # --------------------------------------------------------------------------------------
    regionMessageProtect: true

    # --------------------------------------------------------------------------------------
    # Turn Enable/Disable the protected region message when using the WE\FAWE commands.
    # --------------------------------------------------------------------------------------
    regionMessageProtectWe: true

    # --------------------------------------------------------------------------------------
    # Settings of database.
    # --------------------------------------------------------------------------------------
    dataSource:
        enable: false
        database: wgrp_core
        host: localhost
        port: 3306
        user: root
        password: root
        table: wgrp_logs
        useSsl: true

        # --------------------------------------------------------------------------------------
        # Pool settings...
        # --------------------------------------------------------------------------------------
        maxPoolSize: 10
        maxLifetime: 1800 # 30 minutes
        connectionTimeout: 5000 # 5 second
        intervalReload: 60 # in seconds
