name: WorldGuardRegionProtect
author: RitaSister
version: ${internalVersion}
main: net.ritasister.wgrp.WorldGuardRegionProtect
softdepend: [ WorldGuard ]
description: Protect your region on the server.
website: "https://github.com/RitaSister/WorldGuardRegionProtect"
api-version: 1.16
commands:
  worldguardregionprotect:
   aliases: [wgrp]