name: WorldGuardRegionProtect
version: ${version}
authors: [${author}]
main: ${group}.wgrp.WGRPBukkitPlugin
depend: [ WorldGuard ]
softdepend: [ PlaceholderAPI ]
description: ${description}
website: https://github.com/RSTeamCore/WorldGuardRegionProtect
api-version: 1.19
load: POSTWORLD

permissions:
  wgrp.admin:
    description: All permissions of this plugin
    children:
      - wgrp.command.wgrpbase
      - wgrp.command.reload
      - wgrp.regionprotect
      - wgrp.notify.admin
      - wgrp.command.addregion
      - wgrp.command.removeregion
  wgrp.*:
    description: Alias for wgrp.admin
  wgrp.command.wgrpbase:
    description: Access for /wgrp command
  wgrp.command.addregion:
    description: Access for /wgrp addregion
  wgrp.command.removeregion:
    description: Access for /wgrp removeregion
  wgrp.command.reload:
    description: Access for /wgrp reload command
  wgrp.regionprotect:
    description: Bypass region protect
  wgrp.notify.admin:
    description: See notifies for admins

commands:
  wgregionprotect:
    aliases: [wgrp]
    description: "WGRP Command - main command of WGRP plugin."