name: WorldGuardRegionProtect
authors: [RitaSister, IRedTea]
version: ${internalVersion}
main: net.ritasister.wgrp.WGRPBukkitPlugin
depend: [ WorldGuard ]
softdepend: [ PlaceholderAPI ]
description: Protect your region on the server.
website: 'https://github.com/RSTeamCore/WorldGuardRegionProtect'
api-version: 1.18
load: STARTUP
commands:
  worldguardregionprotect:
   aliases: [wgrp]