[versions]
shadow = "8.1.7"
blossom = "1.3.1"
loom = "1.6-SNAPSHOT"
runPaper = "2.3.0"

[plugins]
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
loom = { id = "fabric-loom", version.ref = "loom" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
