[versions]
shadow = "8.1.1"
blossom = "1.3.1"
loom = "1.3-SNAPSHOT"

[plugins]
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
loom = { id = "fabric-loom", version.ref = "loom" }
